---
date: "Spring 2021"
output:
  html_document:
    toc: yes
    toc_float: yes
---

Kat Devlin
============

-----------------------------------------------
                        
Washington, DC 20009                          
[Linkedin](https://www.linkedin.com/in/kathleendevlin/)  
[Github](https://github.com/KatDevlin)  
Last updated: March 2021
-----------------------------------------------

Objective
---------
Leverage quantitative skill set and international relations knowledge to carry out insightful computational research products for a wide array of technical and non-technical audiences.

Professional Experience
----------

**Research Associate I/II - Global Attitudes & Trends, Pew Research Center**
*Washington, DC; May 2018-Present*

* Manage research agenda, project schedules and $4 million budget proposals for projects that include surveys in 40 countries, globalization focus groups in Western Europe and fieldwork observation in East Africa

* Author of more than 20 reports, op-eds and blog posts on topics such as global perceptions of China, attitudes toward U.S. foreign policy and views of COVID-19-related topics 

* Deliver reports to policymakers, academics, foundations and private sector groups, including Senate Foreign Relations Committee staff, the U.S.-China Business Council and Shell Global

* Collaborate on computational social science projects, including text-as-data analyses with focus group transcripts, structural topic modeling and hierarchical modeling with social media data

* Design survey questionnaires, review country sample plans, manage international fieldwork, perform quality control and assess survey weights using R, SPSS and Stata

**Teaching Fellow - Applied Quantitative Analysis (Dr. Justin Thomas), Yale University**
*New Haven, CT; January-May 2017*

* Taught introductory applied statistics for 30 social science undergraduate students emphasizing statistical concepts such as significance testing, data visualization, linear regression and efficient coding in Stata

**Research Analyst, Pew Research Center**
*Washington, D.C.; March 2013-July 2015*

* Assisted in managing research agenda, tracking project schedules, data management and fact checking 

*	Researched topics for future surveys, such as Chinese soft power, international investment and trade

**English Teaching Assistant, U.S. Fulbright Program**
*Ulu Tiram, Malaysia; January-November 2012*

* Taught conversational English to more than 1,500 high school students in southern Malaysia

* Developed and coordinated English language camps in 14 locations throughout southern Malaysia 

* Secured $500 of equipment from nonprofit organizations and the U.S. Embassy for the school's softball team 

Education
---------

2015-2017
:   **Master's Degree, Global Affairs; concentrations in Quantitative Research Methods and Chinese Studies**  
Yale University - Jackson Institute for Global Affairs (New Haven, CT)  

    *Relevant Coursework:* Applied Methods of Data Analysis, Multivariate Statistics, Advanced Business Analytics with Spreadsheets, Big Data & Global Policies, Microeconomic Principles and Applications, Macroeconomics, Logic of Empirical Research, Economic Strategies for Doing Business in Emerging Markets
    
    *Activities:*  
    Managing Editor for Articles, Yale Journal of International Affairs  
    Member, Yale Law School Wine Society

2007-2011
:   **Bachelor's Degree, Political Science; minor in Chinese Studies**  
Villanova University (Villanova, PA), magna cum laude, honors program


Skills
--------------------

**Technical:** R, Stata, SPSS, HTML, SQL, Git, Word, 
    Excel, PowerPoint, Outlook

**Language:** Mandarin Chinese (advanced, all modalities)

Select Publications
----------------------------------------

* ["As Pandemic Continues, More in U.S. and Europe Feel Major Impact on Their Lives"](https://pewrsr.ch/3oSAfRT)
* ["Legislators in UK, Canada and Australia Express Post-election Enthusiasm for Biden Administration on Twitter"](https://pewrsr.ch/3soMPeg)
* ["How quantitative methods can supplement a qualitative approach when working with focus groups"](https://bit.ly/3oglTKA)
* ["Most Approve of National Response to COVID-19 in 14 Advanced Economies"](https://pewrsr.ch/3gH65gl)
* ["Analyzing international survey data with the pewmethods R package"](https://link.medium.com/tff9fmDBd7)
* ["China’s Economic Growth Mostly Welcomed in Emerging Markets, but Neighbors Wary of Its Influence"](https://pewrsr.ch/2RbL1p0)
* ["Most Japanese think their country’s best days are behind them"](http://po.st/n4U2GP) (Channel NewsAsia op-ed)
* ["U.S.-China Cooperation on Wildlife Smuggling: An Opportunity"](http://www.eastwestcenter.org/publications/us-china-cooperation-wildlife-smuggling-opportunity) (East-West Center op-ed)

Conference Presentations and Papers
----------------------------------------

* “To Pulse or Not to Pulse? The Implications of Pulsing in European CATI Surveys,” American Association of Public Opinion Research 2020. Co-authors: Martha McRoy, Stacy Pancratz and Patrick Moynihan

* “Exploring the link between European political parties’ ideology and their popularity on Twitter,” American Association of Public Opinion Research 2019. Co-author: Adam Hughes

* “The Implications of Sample-Based Versus Self-Reported Measures of Urbanicity,” American Association of Public Opinion Research 2019. Co-authors: Alex Castillo, Janell Fetterold and Courtney Johnson

* “Cultural Diversity Is Associated with Greater Support for Nondemocratic Governance,” American Association of Public Opinion Research 2019. Co-authors: Alex Castillo, Janell Fetterold and Courtney Johnson

Skills and Training
----------------------------------------

* Statistical Analysis: R (tidyverse, lme4, tidymodels, survey), Stata, SPSS, Excel
* Machine Learning: supervised classification (support-vector machines, gradient boosting)
* Text Analysis: word2vec, topic models (LDA, STM)
* Foreign Language: Proficiency in Mandarin Chinese, all modalities
* Volunteer/Affiliations: Council on Foreign Relations, Young Professionals Program, 2018-Present; Freer/Sackler Museum of Asian Art, Member, 2018-Present
* Workshops Attended: Text As Data with R, 3-day seminar with Dr. Brandon Stewart (2020); Multilevel Modeling in R, 3-day seminar with Dr. Stephen Vaisey (2019)